url: https://DylanS-R.github.io
baseurl:

# Site settings
title: Dylan S-R
email: dylan.schmittrayner@gmail.com
description: Test


# Team names, titles and social links
people:
- name: Dylan Schmitt-Rayner
  pic: 1
  position: Lead Designer
  social:
    - title: linkedin
      url: https://linkedin.com/in/dylan-schmitt-rayner-14ba42205
    - title: github
      url: https://github.com/DylanS-R
    - title: stack-overflow
      url: https://stackoverflow.com/users/22382760/dylans-r

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty